branches:
  only:
    - master
    - fb
image:
  - Visual Studio 2019
  - Ubuntu
  - macOS
init:
  - git config --global core.autocrlf true

environment:
  matrix:
    # - nodejs_version: 15
    # - nodejs_version: 14
    # - nodejs_version: 13
    # - nodejs_version: 12
    # - nodejs_version: 11
    # - nodejs_version: 10
    # - nodejs_version: 9
    - nodejs_version: 8

for:
  - matrix:
      only:
        - image: Visual Studio 2019
    install:
      - ps: Install-Product node $env:nodejs_version
    test_script:
      - node --version
      - npm --version
      - npm test -- test001_1

  - matrix:
      only:
        - image: macOS
        - image: Ubuntu
    install:
      - nvm use $nodejs_version
    test_script:
      - node --version
      - npm --version
      - npm test -- test001_1

build: off
